name: CI/CD

on:
  push:
    tags:
      - 'v*.*.*'   # e.g. v1.0.0

permissions:
  id-token: write
  contents: read

jobs:
  build-test-pack:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore Outcome.slnx

      - name: Build
        run: dotnet build Outcome.slnx --configuration Release --no-restore

      - name: Run tests
        run: dotnet test Outcome.slnx --configuration Release --no-build --verbosity normal

      - name: Pack NuGet
        run: dotnet pack src/Outcome/Outcome.csproj --configuration Release --no-build -o ./artifacts
      - name: NuGet login (OIDC â†’ temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}
          
      - name: Add NuGet source
        run: dotnet nuget add source https://api.nuget.org/v3/index.json --name nuget.org --store-password-in-clear-text --username ${{ secrets.NUGET_USER }} --password ${{ steps.login.outputs.NUGET_API_KEY }}
      
      - name: Publish to NuGet
        run: dotnet nuget push ./artifacts/*.nupkg --source nuget.org

      - name: Publish Symbols
        run: dotnet nuget push ./artifacts/*.snupkg --source nuget.org
