name: CI/CD

on:
  push:
    tags:
      - 'v*.*.*'   # e.g. v1.0.0
      
permissions:
  id-token: write
  contents: read

jobs:
  build-test-pack:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Setup NuGet.exe for use with actions
        # You may pin to the exact commit or the version.
        # uses: NuGet/setup-nuget@a21f25cd3998bf370fde17e3f1b4c12c175172f9
        uses: NuGet/setup-nuget@v2.0.0
          
      - name: Restore dependencies
        run: dotnet restore Outcome.slnx

      - name: Build
        run: dotnet build Outcome.slnx --configuration Release --no-restore

      - name: Run tests
        run: dotnet test Outcome.slnx --configuration Release --no-build --verbosity normal
        
      - name: Extract version
        id: version
        run: echo "version=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT
        
      - name: Pack NuGet Outcome
        run: dotnet pack src/Outcome/Outcome.csproj --configuration Release --no-build -o ./artifacts /p:PackageVersion=${{ steps.version.outputs.version }}
      
      - name: Pack NuGet Outcome SourceGenerators
        run: dotnet pack src/Outcome.SourceGenerators/Outcome.SourceGenerators.csproj --configuration Release --no-build -o ./artifacts /p:PackageVersion=${{ steps.version.outputs.version }}
      
      - name: Pack NuGet BbQ.Cqrs
        run: dotnet pack src/BbQ.Cqrs/BbQ.Cqrs.csproj --configuration Release --no-build -o ./artifacts /p:PackageVersion=${{ steps.version.outputs.version }}
      
      - name: Pack NuGet BbQ.Cqrs.SourceGenerators
        run: dotnet pack src/BbQ.Cqrs.SourceGenerators/BbQ.Cqrs.SourceGenerators.csproj --configuration Release --no-build -o ./artifacts /p:PackageVersion=${{ steps.version.outputs.version }}
      
      - name: Pack NuGet BbQ.Events
        run: dotnet pack src/BbQ.Events/BbQ.Events.csproj --configuration Release --no-build -o ./artifacts /p:PackageVersion=${{ steps.version.outputs.version }}
      
      - name: Pack NuGet BbQ.Events.SourceGenerators
        run: dotnet pack src/BbQ.Events.SourceGenerators/BbQ.Events.SourceGenerators.csproj --configuration Release --no-build -o ./artifacts /p:PackageVersion=${{ steps.version.outputs.version }}
      
      - name: NuGet login (OIDC â†’ temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}
    
      - name: Publish to NuGet
        run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json

      - name: Publish Symbols
        run: dotnet nuget push ./artifacts/*.snupkg --api-key ${{steps.login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate

